/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.school;

/**
 *
 * @author charles
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    RegisterStudent regis = new RegisterStudent();
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerStudent = new javax.swing.JButton();
        getoneStudent = new javax.swing.JButton();
        getAllStudent = new javax.swing.JButton();
        registerScore = new javax.swing.JButton();
        updateStudent = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 50, 0, 0));
        setPreferredSize(new java.awt.Dimension(750, 630));
        getContentPane().setLayout(null);

        registerStudent.setBackground(new java.awt.Color(204, 204, 255));
        registerStudent.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registerStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/school/schoolimage/addstudent.jpg"))); // NOI18N
        registerStudent.setText("Register Student");
        registerStudent.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 255)));
        registerStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerStudent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        registerStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        registerStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStudentActionPerformed(evt);
            }
        });
        getContentPane().add(registerStudent);
        registerStudent.setBounds(62, 162, 160, 177);

        getoneStudent.setBackground(new java.awt.Color(204, 204, 255));
        getoneStudent.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getoneStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/school/schoolimage/onestudent.jpg"))); // NOI18N
        getoneStudent.setText("Get one Student");
        getoneStudent.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 255)));
        getoneStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getoneStudent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getoneStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getoneStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getoneStudentActionPerformed(evt);
            }
        });
        getContentPane().add(getoneStudent);
        getoneStudent.setBounds(271, 162, 153, 177);

        getAllStudent.setBackground(new java.awt.Color(204, 204, 255));
        getAllStudent.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getAllStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/school/schoolimage/allstudent.jpg"))); // NOI18N
        getAllStudent.setText("Get All Student");
        getAllStudent.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 255)));
        getAllStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getAllStudent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getAllStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(getAllStudent);
        getAllStudent.setBounds(499, 171, 150, 178);

        registerScore.setBackground(new java.awt.Color(204, 204, 255));
        registerScore.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registerScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/school/schoolimage/score.jpg"))); // NOI18N
        registerScore.setText("Register Score");
        registerScore.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 255)));
        registerScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerScore.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        registerScore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(registerScore);
        registerScore.setBounds(62, 376, 160, 188);

        updateStudent.setBackground(new java.awt.Color(204, 204, 255));
        updateStudent.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updateStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/school/schoolimage/fpage.jpg"))); // NOI18N
        updateStudent.setText("Update Student");
        updateStudent.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 204, 255)));
        updateStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateStudent.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        updateStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        updateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentActionPerformed(evt);
            }
        });
        getContentPane().add(updateStudent);
        updateStudent.setBounds(489, 367, 169, 188);

        back.setBackground(new java.awt.Color(204, 204, 255));
        back.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        back.setText("Logout");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(291, 514, 93, 43);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You are Welcome to Student Information System Font Page");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 6, 721, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("This are the activities you have privilege to Manipulate on");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 36, 721, 26);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please make sure you manage this system properly ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 68, 721, 24);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/school/schoolimage/building1.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 102, 255)));
        jLabel4.setPreferredSize(new java.awt.Dimension(819, 600));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -20, 740, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStudentActionPerformed
        regis.setVisible(true);
    }//GEN-LAST:event_registerStudentActionPerformed

    private void updateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateStudentActionPerformed

    private void getoneStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getoneStudentActionPerformed
        GetOneStudent getone = new GetOneStudent();
        getone.setVisible(true);
                
    }//GEN-LAST:event_getoneStudentActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Loginpage ind = new Loginpage();
        ind.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton getAllStudent;
    private javax.swing.JButton getoneStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton registerScore;
    private javax.swing.JButton registerStudent;
    private javax.swing.JButton updateStudent;
    // End of variables declaration//GEN-END:variables
}
